## Libreria Numpy

In questa lezione andremo ad esplorare una delle librerie più usate in python: Numpy! Innanzitutto facciamo una breve introduzione su cosa siano le librerie. In python è possibile importare funzioni da file separati in modo tale da frammentare il codice che si sta scrivendo ed organizzare il tutto in maniera più snella. Ovviamente, dividere il codice in singole parti che fanno cose differenti non può che aiutarti nel caso vi fossero errori o più in generale ad assegnare ad ogni componente una funzione. Le librerie, o anche moduli, si possono creare come file con estensione '.py', e possono contenere diverse funzioni richiamabili tramite il comando import.

Per quanto riguarda numpy (numerical python), si parla anche qui di una libreria creata da una comunità gigantesca di sviluppatori in modo tale da poter permettere ai programmatori in python di usare immediatamente funzioni che altrimenti dovrebbero inventare loro.

Innanzitutto, importiamo la libreria. Ricordiamo che la libreria dev'essere innanzitutto installata perchè venga trovata! Di conseguenza da terminale sarà necessario il comando 'pip numpy' per installare tale modulo.

In [1]:
import numpy as np

Fatto! Con questa semplice riga abbiamo importato la nuova libreria e possiamo utilizzare tutte le funzioni al suo interno. Il diminutivo 
'np' è arbitrario; ovvero, dato che ogni volta che vogliamo usare una funzione di numpy dovremo dire alla piattaforma di attingere da quella libreria, useremo 'np' come diminutivo per richiamare questo modulo.

Numpy è una libreria che contiene principalmente funzioni matematiche che consentono di effettuare le più svariate operazioni. Di seguito vediamo alcuni di questi comandi. Il protagonista principale di questa libreria è 'l'array', ovvero un vettore. Similmente alla lista, gli array sono contenitori di oggetti (numeri, stringhe...) che godono di proprietà particolari e hanno il grosso vantaggio di poter essere combinati in diversi modi molto semplici.

In [3]:
#definisco un array
a = np.array([1,2,3])
print(a)

[1 2 3]


Come vediamo, l'array è molto simile ad una lista, anche se possiede una sintassi differente. Allo stesso modo delle liste viene indicizzata a partire dallo zero e si possono richiamare le componenti allo stesso modo.

In [4]:
#richiamo le componenti
a0 = a[0]
print(a0)

1


Caratteristica degli array è quello di avere una o più 'dimensioni'. In matematica conosciamo, ad esempio, le matrici: tabelle di numeri formate da righe e colonne. Allo stesso modo gli array (ma anche le liste) possono ramificarsi e contenere altri array.

In [20]:
#definisco una matrice 2x2
matrix = np.array([[1,2,],[3,4]])
print(matrix)

#Come vedo che è una matrice 2x2? Uso il comando shape
dimensione = np.shape(matrix)
print('dimensione matrice: (%i,%i)'%dimensione)

[[1 2]
 [3 4]]
dimensione matrice: (2,2)


In questo caso la matrice è formata da due righe e due colonne. Per accedere a righe e colonne si continua con la sintassi data dagli indici.

Vediamo ora altri modi per definire array di numpy

In [35]:
N=10

#array di tutti zero
z = np.zeros(N)
print(z,np.shape(z))

#array di tutti uno
ones = np.ones(N)
print(ones, np.shape(ones))

#array di tutti numeri uguali
u = np.full(N,5)
print(u,np.shape(u))

#array di sequenze ordinate
s = np.arange(0,N)
s1 = np.arange(0,N,2)      #Il terzo numero in questo caso indica di generare numeri ogni 2
print(s,s1)

#array di numeri equispaziati
e = np.linspace(0,10,100)
print(e, np.shape(e))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (10,)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] (10,)
[5 5 5 5 5 5 5 5 5 5] (10,)
[0 1 2 3 4 5 6 7 8 9] [0 2 4 6 8]
[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.0707070

Come abbiamo anticipato ci sono dei vantaggi nell'utilizzo degli array numpy invece delle liste: banalmente guardiamo qualche operazione!

In [32]:
#definisco una lista e un array uguali
a0 = np.arange(0,N)
l0 = list(range(0,10))

#voglio sommare ad ogni elemento della lista/array un numero
a1 = a0 + 2
l1 = l0 + 2
print(a1,l1)   #cosa succede? ti da errore! questo perchè l'operazione di addizione non è possibile per le liste!

TypeError: can only concatenate list (not "int") to list

In [33]:
#proviamo solo con l'array
a1 = a0 + 2
print(a1)       #ha sommato tutti gli elementi per 2!

[ 2  3  4  5  6  7  8  9 10 11]


In [44]:
#funziona per tutte le operazioni
#sottrazione
print(a0-2)

#moltiplicazione
print(a0*2)

#divisione
print(a0/2)

#elevazione a potenza
print(a0**2)

#somma di array
a = np.array([1,2,3])
b = np.array([3,4,5])
print(a+b)

#seno e coseno
print(np.sin(a))
print(np.cos(b))

[-2 -1  0  1  2  3  4  5  6  7]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 0  1  4  9 16 25 36 49 64 81]
[4 6 8]
[0.84147098 0.90929743 0.14112001]
[-0.9899925  -0.65364362  0.28366219]


### Attenzione quando copi gli array!

Quando vuoi una copia di un array tieni in considerazione che definire un array uguale ad un altro non significa farne una copia, in quanto entrambe le tue variabili verranno indirizzate verso la stessa unità di memoria!

In [40]:
a = np.array([1,2,3])
b = a    #b non è un nuovo array! bensì si riferisce allo stesso contenuto di a
print(b)

#se modifico b modifico anche a!

[1 2 3]


### Altre operazioni con numpy

In [46]:
array = np.arange(0,50)

#massimo
print(np.max(array))

#minimo
print(np.min(array))

#somma 
print(np.sum(array))

49
0
1225


In [51]:
#queste funzioni possono anche essere separate rispetto alle dimensioni: mettiamo caso che io voglia sommare solo le colonne di una matrice
matrice = np.array([[2,4],[5,7]])
max_col = np.sum(matrice, axis=0)
print(max_col)

#sommo le righe
max_righe = np.sum(matrice, axis=1)
print(max_righe)

#questo parametro axis funziona anche con max, min..

[ 7 11]
[ 6 12]


### Unire array

In [56]:
#come mettere insieme array differenti? si può fare sempre tenendo conto delle loro dimensioni!
v1 = np.arange(0,5)
v2 = np.arange(10,15)
v_tot = np.vstack([v1,v2])
print(v_tot)

#in questo caso ha creato una matrice aggiungendo una riga!

v_tot = np.hstack([v1,v2])
print(v_tot)

#in questo caso unisce tutto in modo che si abbia solo una riga

[[ 0  1  2  3  4]
 [10 11 12 13 14]]
[ 0  1  2  3  4 10 11 12 13 14]


### Scaricare dati

numpy ti da la possibilità di scaricare anche dati da file con diversi formati. Prendiamo in esempio un file '.txt' con una serie di numeri casuali.

In [62]:
dati = np.loadtxt('data.txt', delimiter=',')
print(dati)

[[1.0000e+00 2.0000e+00 3.4000e+01 3.4000e+01 5.3200e+02 5.4530e+03
  2.0000e+00 5.6000e+01]
 [3.0000e+00 5.0000e+00 6.0000e+00 3.0000e+00 5.6000e+01 4.0000e+00
  3.0000e+00 6.7000e+01]
 [4.2300e+02 4.2355e+04 2.3150e+03 5.3600e+02 6.4300e+02 2.1000e+01
  3.0000e+00 4.0000e+00]]


Ovviamente il file data.txt è stato creato da me. Importante tenere in conto che siccome il comando np.loadtxt salverà le informazioni del file in un array, queste informazioni devono avere dimensioni consone. In altre parole non posso avere array con differenti dimensioni all'interno del file.

### Booleani

In [65]:
#Vediamo come gli array si comportano con i booleani
a = np.arange(0,20)
print(a>5)       #ho un array in cui ogni elemento viene sottoposto alla condizione a>5

#nuova condizione
print(a==5)

[False False False False False False  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
[False False False False False  True False False False False False False
 False False False False False False False False]


## Esercizio 1:
1) trova tre nuovi comandi di numpy e crea una funzione qualsiasi che li implementi tutti e tre
2) scrivi una funzione che prende in input un array di un numero e restituisca il fattoriale di quel numero
3) Verificare che il prodotto tra una matrice e la sua inversa sia la matrice identità.

## Esercizio 2: 
1) scrivere una funzione che prende in input il grado di un polinomio e i suoi parametri e calcola il suo valore
2) scrivere una funzione che calcoli il determinante di una matrice 

### Sfida: Memory Game

In [8]:
import random
import time

def initialize_memory_board():
    numbers = list(range(1, 9)) * 2
    random.shuffle(numbers)
    board = [numbers[i * 4:(i + 1) * 4] for i in range(4)]
    return board

def print_board(board, revealed):
    for i in range(4):
        for j in range(4):
            if revealed[i][j]:
                print(board[i][j], end=" ")
            else:
                print("X", end=" ")
        print()

def memory_game():
    board = initialize_memory_board()
    revealed = [[False] * 4 for _ in range(4)]
    attempts = 0
    pairs_found = 0

    print("Benvenuto a Memory Game! Trova tutte le coppie.")
    while pairs_found < 8:
        print_board(board, revealed)

        try:
            row1 = int(input("Scegli la prima riga (0-3): "))
            col1 = int(input("Scegli la prima colonna (0-3): "))
            row2 = int(input("Scegli la seconda riga (0-3): "))
            col2 = int(input("Scegli la seconda colonna (0-3): "))
            
            if revealed[row1][col1] or revealed[row2][col2]:
                print("Hai già trovato queste posizioni!")
                continue
            if row1 == row2 and col1 == col2:
                print("Le posizioni devono essere diverse!")
                continue

            attempts += 1
            revealed[row1][col1] = True
            revealed[row2][col2] = True
            print_board(board, revealed)
            
            if board[row1][col1] == board[row2][col2]:
                print("Coppia trovata!")
                pairs_found += 1
            else:
                print("Non è una coppia.")
                revealed[row1][col1] = False
                revealed[row2][col2] = False
                time.sleep(2)

        except (ValueError, IndexError):
            print("Input non valido. Riprova.")
    
    print(f"Complimenti! Hai trovato tutte le coppie in {attempts} tentativi.")

memory_game()


Benvenuto a Blackjack!

La tua mano: [('5', 'Cuori'), ('2', 'Picche')] - Punteggio: 7
Mano del dealer: [('2', 'Fiori'), ('X', 'X')]


Vuoi pescare un'altra carta? (sì o no):  si


Hai pescato: ('3', 'Cuori')
La tua mano: [('5', 'Cuori'), ('2', 'Picche'), ('3', 'Cuori')] - Punteggio: 10


Vuoi pescare un'altra carta? (sì o no):  si


Hai pescato: ('4', 'Quadri')
La tua mano: [('5', 'Cuori'), ('2', 'Picche'), ('3', 'Cuori'), ('4', 'Quadri')] - Punteggio: 14


Vuoi pescare un'altra carta? (sì o no):  si


Hai pescato: ('3', 'Picche')
La tua mano: [('5', 'Cuori'), ('2', 'Picche'), ('3', 'Cuori'), ('4', 'Quadri'), ('3', 'Picche')] - Punteggio: 17


Vuoi pescare un'altra carta? (sì o no):  no


Mano del dealer: [('2', 'Fiori'), ('8', 'Picche')] - Punteggio: 10
Il dealer pesca: ('9', 'Quadri')
Mano del dealer: [('2', 'Fiori'), ('8', 'Picche'), ('9', 'Quadri')] - Punteggio: 19
Il dealer vince. Hai perso.
